# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sx9wSpOKaxSkbm4lKCK8bboGW4-qgkV6
"""

import pandas as pd
data = pd.read_json('/t20_wc_match_results.json')
df = pd.DataFrame(data['matchSummary'].iloc[0])
df.head(5)

df.info()

df.rename(columns={'scorecard':'match_id'},inplace=True)
df.sample()

match_dict = {}
for index,row in df.iterrows():
  key1 = row['team1']+ ' Vs '+row['team2']
  key2 = row['team2']+ ' Vs '+row['team1']
  match_dict[key1]=row['match_id']
  match_dict[key2]=row['match_id']

df.to_csv('/t20_wc_match_results.csv',index=False)

data_bat = pd.read_json('/t20_wc_batting_summary.json')

lst = []
for i in data_bat['battingSummary']:
  lst.extend(i)
df_bat = pd.DataFrame(lst)
df_bat.head()

df_bat.info()

df_bat['runs']=df_bat['runs'].astype(int)
df_bat['balls']=df_bat['balls'].astype(int)
df_bat['4s']=df_bat['4s'].astype(int)
df_bat['6s']=df_bat['6s'].astype(int)
df_bat['SR']=df_bat['SR'].str.replace('-','0.00').astype(float)

df_bat['out/not out'] = df_bat['dismissal'].apply(lambda x:"not out" if len(x)==0 else 'out')
df_bat.sample()

df_bat.drop(['dismissal'],axis=1,inplace=True)
df_bat.sample()

df_bat.rename(columns={'out/not out':'dismissal'},inplace=True)
df_bat.sample()

df_bat['batsmanName']=df_bat['batsmanName'].str.strip('†')
df_bat.head(5)

df_bat['match_id']=df_bat['match'].map(match_dict)
df_bat.head(5)

df_bat.to_csv('/t20_wc_batting_summary.csv',index=False)